restartuninstallPackage"SpectralSequences"
+ M2 --no-readline --print-width 79
Macaulay2, version 1.9
with packages: ConwayPolynomials, Elimination, IntegralClosure, LLLBases,
               PrimaryDecomposition, ReesAlgebra, TangentCone

i1 : restart
Macaulay2, version 1.9
with packages: ConwayPolynomials, Elimination, IntegralClosure, LLLBases,
               PrimaryDecomposition, ReesAlgebra, TangentCone

i1 : uninstallPackage"SpectralSequences"

i2 : installPackage"SpectralSequences"
--installing package SpectralSequences in ../../../../Library/Application Support/Macaulay2/local/
--using package sources found in /Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/
--storing raw documentation in ../../../../Library/Application Support/Macaulay2/local/lib/Macaulay2/x86_64-Darwin-MacOS-10.11.3/SpectralSequences/cache/rawdocumentation-dcba-8.db
--running tests that are functions
--making example result files in ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/
--making example results for spectralSequencePage(FilteredComplex,ZZ) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_spectral__Sequence__Page_lp__Filtered__Complex_cm__Z__Z_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/1-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_spectral__Sequence__Page_lp__Filtered__Complex_cm__Z__Z_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_spectral__Sequence__Page_lp__Filtered__Complex_cm__Z__Z_rp.errors" 2>&1
--making example results for prunningMaps in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_prunning__Maps.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/2-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_prunning__Maps.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_prunning__Maps.errors" 2>&1
--making example results for Filtrations and homomorphism complexes in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Filtrations_spand_sphomomorphism_spcomplexes.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/3-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Filtrations_spand_sphomomorphism_spcomplexes.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Filtrations_spand_sphomomorphism_spcomplexes.errors" 2>&1
--making example results for Spectral sequences and hypercohomology calculations in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral_spsequences_spand_sphypercohomology_spcalculations.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/4-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Spectral_spsequences_spand_sphypercohomology_spcalculations.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral_spsequences_spand_sphypercohomology_spcalculations.errors" 2>&1
--making example results for minimalPresentation(SpectralSequencePage) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_minimal__Presentation_lp__Spectral__Sequence__Page_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/5-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_minimal__Presentation_lp__Spectral__Sequence__Page_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_minimal__Presentation_lp__Spectral__Sequence__Page_rp.errors" 2>&1
--making example results for FilteredComplex ^ ZZ in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Filtered__Complex_sp^_sp__Z__Z.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/6-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Filtered__Complex_sp^_sp__Z__Z.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Filtered__Complex_sp^_sp__Z__Z.errors" 2>&1
--making example results for ChainComplex ** FilteredComplex in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Chain__Complex_sp_st_st_sp__Filtered__Complex.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/7-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Chain__Complex_sp_st_st_sp__Filtered__Complex.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Chain__Complex_sp_st_st_sp__Filtered__Complex.errors" 2>&1
--making example results for Edge homomorphisms in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Edge_sphomomorphisms.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/8-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Edge_sphomomorphisms.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Edge_sphomomorphisms.errors" 2>&1
--making example results for truncate(ChainComplex,ZZ) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_truncate_lp__Chain__Complex_cm__Z__Z_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/9-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_truncate_lp__Chain__Complex_cm__Z__Z_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_truncate_lp__Chain__Complex_cm__Z__Z_rp.errors" 2>&1
--making example results for Balancing Tor in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Balancing_sp__Tor.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/10-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Balancing_sp__Tor.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Balancing_sp__Tor.errors" 2>&1
--making example results for filteredComplex(Ideal,ChainComplex,ZZ) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_filtered__Complex_lp__Ideal_cm__Chain__Complex_cm__Z__Z_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/11-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_filtered__Complex_lp__Ideal_cm__Chain__Complex_cm__Z__Z_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_filtered__Complex_lp__Ideal_cm__Chain__Complex_cm__Z__Z_rp.errors" 2>&1
--making example results for Computing the Serre Spectral Sequence associated to a Hopf Fibration in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Computing_spthe_sp__Serre_sp__Spectral_sp__Sequence_spassociated_spto_spa_sp__Hopf_sp__Fibration.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/12-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Computing_spthe_sp__Serre_sp__Spectral_sp__Sequence_spassociated_spto_spa_sp__Hopf_sp__Fibration.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Computing_spthe_sp__Serre_sp__Spectral_sp__Sequence_spassociated_spto_spa_sp__Hopf_sp__Fibration.errors" 2>&1
--making example results for I-adic filtrations of chain complexes and their spectral sequences in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___I-adic_spfiltrations_spof_spchain_spcomplexes_spand_sptheir_spspectral_spsequences.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/13-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___I-adic_spfiltrations_spof_spchain_spcomplexes_spand_sptheir_spspectral_spsequences.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___I-adic_spfiltrations_spof_spchain_spcomplexes_spand_sptheir_spspectral_spsequences.errors" 2>&1
--making example results for filteredComplex(SpectralSequence) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_filtered__Complex_lp__Spectral__Sequence_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/14-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_filtered__Complex_lp__Spectral__Sequence_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_filtered__Complex_lp__Spectral__Sequence_rp.errors" 2>&1
--making example results for SpectralSequence ^ ZZ in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral__Sequence_sp^_sp__Z__Z.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/15-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Spectral__Sequence_sp^_sp__Z__Z.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral__Sequence_sp^_sp__Z__Z.errors" 2>&1
--making example results for A spectral sequence with nonzero maps on every page. in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___A_spspectral_spsequence_spwith_spnonzero_spmaps_spon_spevery_sppage..out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/16-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___A_spspectral_spsequence_spwith_spnonzero_spmaps_spon_spevery_sppage..m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___A_spspectral_spsequence_spwith_spnonzero_spmaps_spon_spevery_sppage..errors" 2>&1
../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___A_spspectral_spsequence_spwith_spnonzero_spmaps_spon_spevery_sppage..errors:0:1: (output file) error: Macaulay2 exited with status code 1
stdio:14:32:(3):[4]: error: can't promote number to ring
/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___A_spspectral_spsequence_spwith_spnonzero_spmaps_spon_spevery_sppage..m2:0:1: (input file)
M2: *** Error 1
--making example results for Spectral sequences and non-Koszul syzygies in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral_spsequences_spand_spnon-__Koszul_spsyzygies.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/17-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Spectral_spsequences_spand_spnon-__Koszul_spsyzygies.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral_spsequences_spand_spnon-__Koszul_spsyzygies.errors" 2>&1
--making example results for support(ChainComplex) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_support_lp__Chain__Complex_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/18-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_support_lp__Chain__Complex_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_support_lp__Chain__Complex_rp.errors" 2>&1
--making example results for chainComplex(FilteredComplex) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_chain__Complex_lp__Filtered__Complex_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/19-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_chain__Complex_lp__Filtered__Complex_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_chain__Complex_lp__Filtered__Complex_rp.errors" 2>&1
--making example results for chainComplex(SpectralSequence) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_chain__Complex_lp__Spectral__Sequence_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/20-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_chain__Complex_lp__Spectral__Sequence_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_chain__Complex_lp__Spectral__Sequence_rp.errors" 2>&1
--making example results for PageMap in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Page__Map.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/21-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Page__Map.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Page__Map.errors" 2>&1
--making example results for Page in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Page.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/22-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Page.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Page.errors" 2>&1
--making example results for hilbertPolynomial(SpectralSequencePage) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_hilbert__Polynomial_lp__Spectral__Sequence__Page_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/23-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_hilbert__Polynomial_lp__Spectral__Sequence__Page_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_hilbert__Polynomial_lp__Spectral__Sequence__Page_rp.errors" 2>&1
--making example results for edgeComplex in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_edge__Complex.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/24-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_edge__Complex.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_edge__Complex.errors" 2>&1
--making example results for SpectralSequencePageMap ^ List in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral__Sequence__Page__Map_sp^_sp__List.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/25-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Spectral__Sequence__Page__Map_sp^_sp__List.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral__Sequence__Page__Map_sp^_sp__List.errors" 2>&1
--making example results for inducedMap(FilteredComplex,ZZ) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_induced__Map_lp__Filtered__Complex_cm__Z__Z_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/26-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_induced__Map_lp__Filtered__Complex_cm__Z__Z_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_induced__Map_lp__Filtered__Complex_cm__Z__Z_rp.errors" 2>&1
--making example results for Spectral sequences and connecting morphisms in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral_spsequences_spand_spconnecting_spmorphisms.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/27-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Spectral_spsequences_spand_spconnecting_spmorphisms.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral_spsequences_spand_spconnecting_spmorphisms.errors" 2>&1
--making example results for filtered complexes and spectral sequences from simplicial complexes in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_filtered_spcomplexes_spand_spspectral_spsequences_spfrom_spsimplicial_spcomplexes.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/28-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_filtered_spcomplexes_spand_spspectral_spsequences_spfrom_spsimplicial_spcomplexes.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_filtered_spcomplexes_spand_spspectral_spsequences_spfrom_spsimplicial_spcomplexes.errors" 2>&1
--making example results for spectralSequence in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_spectral__Sequence.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/29-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_spectral__Sequence.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_spectral__Sequence.errors" 2>&1
--making example results for A spectral sequence which fails to degenerate quickly in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___A_spspectral_spsequence_spwhich_spfails_spto_spdegenerate_spquickly.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/30-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___A_spspectral_spsequence_spwhich_spfails_spto_spdegenerate_spquickly.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___A_spspectral_spsequence_spwhich_spfails_spto_spdegenerate_spquickly.errors" 2>&1
--making example results for Hom(FilteredComplex,ChainComplex) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Hom_lp__Filtered__Complex_cm__Chain__Complex_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/31-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Hom_lp__Filtered__Complex_cm__Chain__Complex_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Hom_lp__Filtered__Complex_cm__Chain__Complex_rp.errors" 2>&1
--making example results for homologyIsomorphism(SpectralSequence,ZZ,ZZ,ZZ) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_homology__Isomorphism_lp__Spectral__Sequence_cm__Z__Z_cm__Z__Z_cm__Z__Z_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/32-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_homology__Isomorphism_lp__Spectral__Sequence_cm__Z__Z_cm__Z__Z_cm__Z__Z_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_homology__Isomorphism_lp__Spectral__Sequence_cm__Z__Z_cm__Z__Z_cm__Z__Z_rp.errors" 2>&1
--making example results for Filtrations and tensor product complexes in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Filtrations_spand_sptensor_spproduct_spcomplexes.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/33-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Filtrations_spand_sptensor_spproduct_spcomplexes.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Filtrations_spand_sptensor_spproduct_spcomplexes.errors" 2>&1
--making example results for The fibration of the Klein Bottle over the sphere with fibers the sphere in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___The_spfibration_spof_spthe_sp__Klein_sp__Bottle_spover_spthe_spsphere_spwith_spfibers_spthe_spsphere.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/34-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___The_spfibration_spof_spthe_sp__Klein_sp__Bottle_spover_spthe_spsphere_spwith_spfibers_spthe_spsphere.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___The_spfibration_spof_spthe_sp__Klein_sp__Bottle_spover_spthe_spsphere_spwith_spfibers_spthe_spsphere.errors" 2>&1
--making example results for SpectralSequencePage ^ List in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral__Sequence__Page_sp^_sp__List.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/35-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Spectral__Sequence__Page_sp^_sp__List.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral__Sequence__Page_sp^_sp__List.errors" 2>&1
--making example results for basis(List,SpectralSequencePage) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_basis_lp__List_cm__Spectral__Sequence__Page_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/36-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_basis_lp__List_cm__Spectral__Sequence__Page_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_basis_lp__List_cm__Spectral__Sequence__Page_rp.errors" 2>&1
--making example results for spectralSequence(FilteredComplex) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_spectral__Sequence_lp__Filtered__Complex_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/37-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_spectral__Sequence_lp__Filtered__Complex_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_spectral__Sequence_lp__Filtered__Complex_rp.errors" 2>&1
--making example results for minimalPresentation(SpectralSequence) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_minimal__Presentation_lp__Spectral__Sequence_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/38-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_minimal__Presentation_lp__Spectral__Sequence_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_minimal__Presentation_lp__Spectral__Sequence_rp.errors" 2>&1
--making example results for SpectralSequencePageMap _ List in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral__Sequence__Page__Map_sp_us_sp__List.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/39-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Spectral__Sequence__Page__Map_sp_us_sp__List.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral__Sequence__Page__Map_sp_us_sp__List.errors" 2>&1
--making example results for Example 1 in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Example_sp1.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/40-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Example_sp1.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Example_sp1.errors" 2>&1
--making example results for changeOfRingsTor in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_change__Of__Rings__Tor.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/41-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_change__Of__Rings__Tor.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_change__Of__Rings__Tor.errors" 2>&1
--making example results for Example 2 in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Example_sp2.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/42-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Example_sp2.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Example_sp2.errors" 2>&1
--making example results for filteredComplex(List) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_filtered__Complex_lp__List_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/43-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_filtered__Complex_lp__List_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_filtered__Complex_lp__List_rp.errors" 2>&1
--making example results for Example 3 in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Example_sp3.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/44-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Example_sp3.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Example_sp3.errors" 2>&1
--making example results for filteredComplex(ChainComplex) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_filtered__Complex_lp__Chain__Complex_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/45-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_filtered__Complex_lp__Chain__Complex_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_filtered__Complex_lp__Chain__Complex_rp.errors" 2>&1
--making example results for SpectralSequencePage _ List in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral__Sequence__Page_sp_us_sp__List.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/46-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Spectral__Sequence__Page_sp_us_sp__List.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral__Sequence__Page_sp_us_sp__List.errors" 2>&1
--making example results for tensor(RingMap,ChainComplex) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_tensor_lp__Ring__Map_cm__Chain__Complex_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/47-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_tensor_lp__Ring__Map_cm__Chain__Complex_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_tensor_lp__Ring__Map_cm__Chain__Complex_rp.errors" 2>&1
--making example results for Identifying anti-podal points of the two sphere in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Identifying_spanti-podal_sppoints_spof_spthe_sptwo_spsphere.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/48-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Identifying_spanti-podal_sppoints_spof_spthe_sptwo_spsphere.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Identifying_spanti-podal_sppoints_spof_spthe_sptwo_spsphere.errors" 2>&1
--making example results for How to make filtered complexes from chain complex maps in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___How_spto_spmake_spfiltered_spcomplexes_spfrom_spchain_spcomplex_spmaps.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/49-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___How_spto_spmake_spfiltered_spcomplexes_spfrom_spchain_spcomplex_spmaps.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___How_spto_spmake_spfiltered_spcomplexes_spfrom_spchain_spcomplex_spmaps.errors" 2>&1
--making example results for prunningMaps(SpectralSequencePage) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_prunning__Maps_lp__Spectral__Sequence__Page_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/50-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_prunning__Maps_lp__Spectral__Sequence__Page_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_prunning__Maps_lp__Spectral__Sequence__Page_rp.errors" 2>&1
--making example results for spectralSequencePage in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_spectral__Sequence__Page.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/51-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_spectral__Sequence__Page.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_spectral__Sequence__Page.errors" 2>&1
--making example results for The trivial fibration over the sphere with fibers the sphere in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___The_sptrivial_spfibration_spover_spthe_spsphere_spwith_spfibers_spthe_spsphere.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/52-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___The_sptrivial_spfibration_spover_spthe_spsphere_spwith_spfibers_spthe_spsphere.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___The_sptrivial_spfibration_spover_spthe_spsphere_spwith_spfibers_spthe_spsphere.errors" 2>&1
--making example results for Filtered complexes and simplicial complexes in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Filtered_spcomplexes_spand_spsimplicial_spcomplexes.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/53-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Filtered_spcomplexes_spand_spsimplicial_spcomplexes.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Filtered_spcomplexes_spand_spsimplicial_spcomplexes.errors" 2>&1
--making example results for SpectralSequence _ ZZ in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral__Sequence_sp_us_sp__Z__Z.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/54-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0___Spectral__Sequence_sp_us_sp__Z__Z.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/___Spectral__Sequence_sp_us_sp__Z__Z.errors" 2>&1
--making example results for netPage(Page,List,List) in file ../../../../Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_net__Page_lp__Page_cm__List_cm__List_rp.out
ulimit -t 700; ulimit -m 850000; ulimit -v 850000; ulimit -s 8192; cd /var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/55-rundir/; /Applications/Macaulay2-1.9/bin/M2-binary --silent --print-width 77 --stop --int --no-readline --no-randomize -e 'needsPackage("SpectralSequences", FileName => "/Users/nathangrieve/Documents/NathanCode/Workshop-2016-Utah/SpectralSequences/SpectralSequences.m2")' <"/var/folders/78/bp13r4gx6gx369r4z_yg01nh0000gn/T/M2-2741-0/0_net__Page_lp__Page_cm__List_cm__List_rp.m2" >>"/Users/nathangrieve/Library/Application Support/Macaulay2/local/share/doc/Macaulay2/SpectralSequences/example-output/_net__Page_lp__Page_cm__List_cm__List_rp.errors" 2>&1
stdio:2:1:(3): error: 1 error(s) occurred running examples for package SpectralSequences

i3 : 